#!/bin/bash
# first parameter ($1) is directory to create lab. defaults to current dir
# set -euo pipefail
# only RIP and OSPF router config

IFS='' read -r -d '' DAEMONSPRE <<"EOF"
# This file tells the frr package which daemons to start.
#
# Sample configurations for these daemons can be found in
# /usr/share/doc/frr/examples/.
#
# ATTENTION:
#
# When activating a daemon for the first time, a config file, even if it is
# empty, has to be present *and* be owned by the user and group "frr", else
# the daemon will not be started by /etc/init.d/frr. The permissions should
# be u=rw,g=r,o=.
# When using "vtysh" such a config file is also needed. It should be owned by
# group "frrvty" and set to ug=rw,o= though. Check /etc/pam.d/frr, too.
#
# The watchfrr, zebra and staticd daemons are always started.
#
bgpd=no
EOF
IFS='' read -r -d '' DAEMONSPOST <<"EOF"
ripngd=no
isisd=no
pimd=no
pim6d=no
ldpd=no
nhrpd=no
eigrpd=no
babeld=no
sharpd=no
pbrd=no
bfdd=no
fabricd=no
vrrpd=no
pathd=no

#
# If this option is set the /etc/init.d/frr script automatically loads
# the config via "vtysh -b" when the servers are started.
# Check /etc/pam.d/frr if you intend to use "vtysh"!
#
vtysh_enable=yes
zebra_options="  -A 127.0.0.1 -s 90000000"
mgmtd_options="  -A 127.0.0.1"
bgpd_options="   -A 127.0.0.1"
ospfd_options="  -A 127.0.0.1"
ospf6d_options=" -A ::1"
ripd_options="   -A 127.0.0.1"
ripngd_options=" -A ::1"
isisd_options="  -A 127.0.0.1"
pimd_options="   -A 127.0.0.1"
pim6d_options="  -A ::1"
ldpd_options="   -A 127.0.0.1"
nhrpd_options="  -A 127.0.0.1"
eigrpd_options=" -A 127.0.0.1"
babeld_options=" -A 127.0.0.1"
sharpd_options=" -A 127.0.0.1"
pbrd_options="   -A 127.0.0.1"
staticd_options="-A 127.0.0.1"
bfdd_options="   -A 127.0.0.1"
fabricd_options="-A 127.0.0.1"
vrrpd_options="  -A 127.0.0.1"
pathd_options="  -A 127.0.0.1"


# If you want to pass a common option to all daemons, you can use the
# "frr_global_options" variable.
#
#frr_global_options=""


# The list of daemons to watch is automatically generated by the init script.
# This variable can be used to pass options to watchfrr that will be passed
# prior to the daemon list.
#
# To make watchfrr create/join the specified netns, add the the "--netns"
# option here. It will only have an effect in /etc/frr/<somename>/daemons, and
# you need to start FRR with "/usr/lib/frr/frrinit.sh start <somename>".
#
#watchfrr_options=""


# configuration profile
#
#frr_profile="traditional"
#frr_profile="datacenter"


# This is the maximum number of FD's that will be available.  Upon startup this
# is read by the control files and ulimit is called.  Uncomment and use a
# reasonable value for your setup if you are expecting a large number of peers
# in say BGP.
#
#MAX_FDS=1024

# Uncomment this option if you want to run FRR as a non-root user. Note that
# you should know what you are doing since most of the daemons need root
# to work. This could be useful if you want to run FRR in a container
# for instance.
# FRR_NO_ROOT="yes"

# For any daemon, you can specify a "wrap" command to start instead of starting
# the daemon directly. This will simply be prepended to the daemon invocation.
# These variables have the form daemon_wrap, where 'daemon' is the name of the
# daemon (the same pattern as the daemon_options variables).
#
# Note that when daemons are started, they are told to daemonize with the `-d`
# option. This has several implications. For one, the init script expects that
# when it invokes a daemon, the invocation returns immediately. If you add a
# wrap command here, it must comply with this expectation and daemonize as
# well, or the init script will never return. Furthermore, because daemons are
# themselves daemonized with -d, you must ensure that your wrapper command is
# capable of following child processes after a fork() if you need it to do so.
#
# If your desired wrapper does not support daemonization, you can wrap it with
# a utility program that daemonizes programs, such as 'daemonize'. An example
# of this might look like:
#
# bgpd_wrap="/usr/bin/daemonize /usr/bin/mywrapper"
#
# This is particularly useful for programs which record processes but lack
# daemonization options, such as perf and rr.
#
# If you wish to wrap all daemons in the same way, you may set the "all_wrap"
# variable.
#
#all_wrap=""
EOF



echo -e 'Quick and dirty lab setup (editor) script, works for RIP and OSPF. No error correction included... Use at your own risk\n\n'

HOSTS=()
LABPATH=$1
if [ -z "${LABPATH}" ]; then
    LABPATH='.'
fi

read -p "Enter Hostname(s) ('q' to quit): " HOST
while ( ! [ $HOST = "q" ] && ! [ $HOST = "Q" ] ); do
    HOSTS+=( "$HOST" )
    mkdir -p "$LABPATH/$HOST"
    touch "$LABPATH/$HOST.startup"
    echo -e "Created '$HOST/' and '$HOST.startup' \n"


    read -p "Enter Hostname(s) ('q' to quit): " HOST
done
echo -e $'######################################\n'
echo -e "Hosts:"
for host in "${HOSTS[@]}" ; do echo "$host"; done 
echo -e $'\n######################################'


# echo -e '\nConfig lab.conf:\n'
read -p "Select Host ('q' to quit): " HOST
LABCONF=''
ETHCONF=''
ROUTECONF=''
STARTUPOPT=''
VTYCONF=''
FRRCONF=''
DAEMONS=''
while ( ! [ $HOST = "q" ] && ! [ $HOST = "Q" ] ); do

    FOUND="q"
    for x in "${HOSTS[@]}"; do
        if [ "$x" = "$HOST" ]; then
            FOUND="y"
            echo -e "[$HOST]> Select option: "
            echo -e "'1': add interface"
            echo -e "'2': add route"
            echo -e "'3': add routing options"
            echo -e "'4': view config"
            echo -e "'5': (over)write config to file(s)"
            echo -e "'6': (over)write config to lab.conf"
            echo -e "'q': select another host"
            read -p "> " OPT

            if [ "$OPT" = "1" ]; then
                read -p "[$HOST]> Enter interface number (eth[x]): " ETH
                read -p "[$HOST]> Enter collision domain: " DOM
                read -p "[$HOST(eth$ETH)]> Enter MAC address (xx:xx:xx:xx:xx:xx) [optional]: " MAC
                read -p "[$HOST(eth$ETH)]> Enter IPv4 address (x.x.x.x/yy): " IP
                ETHCONF=$ETHCONF"ip address add $IP dev eth$ETH\n"
                if [ -z "${MAC}" ]; then
                    LABCONF=$LABCONF"$HOST[$ETH]=$DOM\n"
                else
                    LABCONF=$LABCONF"$HOST[$ETH]=$DOM/$MAC\n"
                fi
            elif [ "$OPT" = "2" ]; then
                read -p "[$HOST]> Enter source interface number (eth[x]): " ETH
                read -p "[$HOST(eth$ETH)]> Enter nexthop IPv4 address (x.x.x.x): " HOP
                read -p "[$HOST(eth$ETH)]($HOP) -> ...> Enter target IPv4 address (x.x.x.x/yy): " TRG
                echo -e "[$HOST(eth$ETH)]($HOP) -> ($TRG)"
                ROUTECONF=$ROUTECONF"ip route add $TRG via $HOP dev eth$ETH\n"
            elif [ "$OPT" = "3" ]; then
                read -p "[$HOST]> Enable frr? [Y/n]" FRR
                if [ "$FRR" = "y" ] || [ "$FRR" = "Y" ] || [ -z "$FRR" ]; then
                    STARTUPOPT=$STARTUPOPT"systemctl start frr"
                    mkdir -p "$LABPATH/$HOST/etc/frr"
                    echo -e "Created [$HOST]/etc/frr"
                    read -p "[$HOST(frr)]> Enable vtysh integrated config? [Y/n]" VTY
                    if [ "$VTY" = "y" ] || [ "$VTY" = "Y" ] || [ -z "$VTY" ]; then
                        VTYCONF="service integrated-vtysh-config"
                    else
                        VTYCONF="no service integrated-vtysh-config"
                    fi
                    while :
                    do
                        echo -e "[$HOST(frr)]> Select option:"
                        echo -e $"'1': add RIP\n'2': add OSPF\n'3': view config'q': quit"
                        read -p ">" RTR
                        if [ "$RTR" = "1" ]; then
                            FRRCONF='router rip\n'
                            DAEMONS='ospfd=no\nospf6d=no\nripd\=yes'
                            while :
                            do
                                echo -e "[$HOST(frr:RIP)]> Choose option:"
                                echo -e "'1': add network"
                                echo -e "'2': add route"
                                echo -e "'4': redistribute connected?"
                                echo -e "'5': redistribute kernel?"
                                echo -e "'q': quit RIP"
                                read -p ">" RIP
                                if [ "$RIP" = "1" ]; then
                                    read -p "[$HOST(frr:RIP)]> Enter network IPv4 address (x.x.x.x/yy):" IP
                                    FRRCONF=$FRRCONF"network $IP\n"
                                elif [ "$RIP" = "2" ]; then
                                    read -p "[$HOST(frr:RIP)]> Enter route IPv4 address (x.x.x.x/yy):" IP
                                    FRRCONF=$FRRCONF"route $IP\n"
                                elif [ "$RIP" = "3" ]; then
                                    FRRCONF=$FRRCONF"redistribute connected\n"
                                elif [ "$RIP" = "4" ]; then
                                    FRRCONF=$FRRCONF"redistribute kernel\n"
                                elif [ "$RIP" = "q" ]; then
                                    break
                                fi
                            done
                        elif [ "$RTR" = "2" ]; then
                            FRRCONF='router ospf\n'
                            DAEMONS='ospfd=yes\nospf6d=no\nripd=no\n'
                            while :
                            do
                                echo -e "[$HOST(frr:OSPF)]> Choose option:"
                                echo -e "'1': add network"
                                echo -e "'2': add area"
                                echo -e "'3': add interface costs"
                                echo -e "'4': redistribute connected?"
                                echo -e "'5': redistribute kernel?"
                                echo -e "'q': quit OSPF"
                                read -p ">" OSPF
                                if [ "$OSPF" = "1" ]; then
                                    read -p "[$HOST(frr:OSPF)]> Enter network (x.x.x.x/yy):" IP
                                    read -p "[$HOST(frr:OSPF)]> Enter area ID (z.z.z.z):" AREA
                                    FRRCONF=$FRRCONF"network $IP area $AREA"
                                elif [ "$OSPF" = "2" ]; then
                                    read -p "[$HOST(frr:OSPF)]> Enter area ID (z.z.z.z):" AREA
                                    read -p "[$HOST(frr:OSPF)]> Enter area type:" TYPE
                                    read -p "[$HOST(frr:OSPF)]> Enter additional option (no-summary/...):" OPTS
                                    FRRCONF=$FRRCONF"area $AREA $TYPE $OPTS"
                                elif [ "$OSPF" = "3" ]; then
                                    read -p "[$HOST(frr:OSPF)]> Enter interface number:" ETH
                                    read -p "[$HOST(frr:OSPF)(eth$ETH)]> Enter interface cost:" CST
                                    FRRCONF=$FRRCONF"interface eth$ETH\nospf cost $CST"
                                elif [ "$OSPF" = "4" ]; then
                                    FRRCONF=$FRRCONF"redistribute connected"                                    
                                elif [ "$OSPF" = "5" ]; then
                                    FRRCONF=$FRRCONF"redistribute kernel"
                                elif [ "$OSPF" = "q" ]; then
                                    break
                                fi
                            done
                        elif [ "$RTR" = "3" ]; then
                            echo -e "'vtysh.conf':\n$VTYCONF\n'frr.conf':\n$FRRCONF\n'daemons':\n$DAEMONS\n"
                        elif [ "$RTR" = "q" ]; then
                            # echo -e "Aborting. Clearing conf..."
                            # VTYCONF=''
                            # FRRCONF=''
                            # DAEMONS=''
                            FRRCONF=$FRRCONF"log file /var/log/frr/frr.log"
                            break
                        fi
                    done
                fi
            elif [ "$OPT" = "4" ]; then
                echo -e $'######################################\n'
                echo -e "Saved config(s):"
                for host in "${HOSTS[@]}" ; do 
                    echo -e "'[$host].startup':"
                    cat "$LABPATH/$host.startup" 
                    echo -e "'[$host]/etc/frr':"
                    echo -e "'vtysh.conf'":
                    cat "$LABPATH/$HOST/etc/frr/vtysh.conf"
                    echo -e "'frr.conf'":
                    cat "$LABPATH/$HOST/etc/frr/frr.conf"
                    echo -e "'daemons'":
                    cat "$LABPATH/$HOST/etc/frr/daemons"                    
                done
                echo -e "Working config(s):" 
                echo -e "'[$HOST].startup*':"
                echo -e "$ETHCONF$ROUTECONF$STARTUPOPT"
                echo -e "\n'lab.conf*':"
                echo -e "$LABCONF"
                echo -e $'\n######################################'
            elif [ "$OPT" = "5" ]; then
                echo -e "(Over)Writing to [$HOST].startup..."
                echo -e "$ETHCONF$ROUTECONF$STARTUPOPT" > "$LABPATH/$HOST.startup"
                # mkdir -p "$LABPATH/etc/frr"
                echo -e "(Over)Writing to [$HOST]/etc/frr/vtysh.conf..."
                echo -e "$VTYCONF" > "$LABPATH/$HOST/etc/frr/vtysh.conf"
                echo -e "(Over)Writing to [$HOST]/etc/frr/frr.conf..."
                echo -e "$FRRCONF" > "$LABPATH/$HOST/etc/frr/frr.conf"
                echo -e "(Over)Writing to [$HOST]/etc/frr/daemons..."
                echo -e "$DAEMONSPRE$DAEMONS$DAEMONSPOST" > "$LABPATH/$HOST/etc/frr/daemons"
                echo -e "Saved $HOST config!"
            elif [ "$OPT" = "6" ]; then
                echo -e "(Over)Writing 'lab.conf'..."
                touch "$LABPATH/lab.conf"
                echo -e "$LABCONF" > "$LABPATH/lab.conf"
                echo -e "Sav(Over)Writinged 'lab.conf'!"
            fi
        fi
    done
    
    if [[ $FOUND = "q" ]]; then
        echo -e "'$HOST' does not exist in current lab"
    fi
    if [[ $OPT = "q" ]]; then
        read -p "Select Host ('q' to quit): " HOST
        ETHCONF=''
        ROUTECONF=''
        STARTUPOPT=''
        VTYCONF=''
        FRRCONF=''
        DAEMONS=''
    fi
done

echo -e "Finished editing:"
echo -e "$LABCONF"
read -p "(Over)Write config to 'lab.conf'? [y/N]" LAB
if [ "$LAB" = "y" ] || [ "$LAB" = "Y" ]; then
    echo -e "Saving config..."
    echo -e "$LABCONF" > "$LABPATH/lab.conf"
    echo -e "Saved config!"
fi
echo -e "Closing"

